### ISSUE TITLE
ERROR: your API version (17) does not support the required calls. You'll need API version 1.8 (11.1) or higher!

### ISSUE THREAD

**Issue by hdaz000700** [stdevel/check_repodata#5]
Hi is there any plans to update the check for newer version of spacewalk ?

currently using 2.5 but 2.6 is also released.

Warm Regards

**Comment by stdevel** [comment]
Hey hdaz000700,
sorry for the late answer!

Updated the utility in commit e5c137570d58d19e7e0b1923f5610b6ed03d225e - and I will also add a parameter soon to ignore warnings like this in the future - see also issue #6.

Does this work for you, now?
